info = []
name = input("enter your name: ")
info.append(name)
lastname = input("enter your last name: ")
info.append(lastname)
age = input("enter your age: ")
info.append(age)
weight = input("enter your weight: ")
info.append(weight)
height = input("enter your height: ")
info.append(height)
birth_date = input("enter your birthdate: ")
info.append(birth_date)
country = input("enter your country: ")
info.append(country)
phone_number = input("enter your phone number: ")
info.append(phone_number)
print(info)
    